layout: stacked
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

repository: ryansiu1995/personal-wbesite

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 3
  exclude:
    archived: false
    forks: false
    projects:
    - personal-website

social_media:
  # behance: your_username
  # dribbble: your_username
  facebook: SiuL.W.Ryan
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: ryansiu1995
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  telegram: ryansiu
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Elixir
    web_url: https://github.com/topics/Elixir
    image_url: https://raw.githubusercontent.com/github/explore/d106aa3f6fa091ab80ab5c8cf0d931baff3caaea/topics/elixir/elixir.png
  - name: Kubernetes
    web_url: https://github.com/topics/kubernetes
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/kubernetes/kubernetes.png
  - name: Golang
    web_url: https://github.com/topics/Golang
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/go/go.png
